openapi: 3.0.1
info:
  title: Analytics.Conceptual.Service.Interfaces.Public.V1 AnnotationService Client Side Libraries Module API
  description: Analytics.Conceptual.Service.Interfaces.Public
  version: V1
servers:
- url: /Relativity.REST/api
  description: The URL prefix for all Kepler services
tags:
- name: Client Side Libraries Module
paths:
  /import-service/v1/client-side-libraries/{fileName}/:
    get:
      tags:
      - Client Side Libraries Module
      summary: ''
      description: Get a script by name.
      operationId: Import.Services.V1.ClientSideLibrariesController.GetScript
      parameters:
      - $ref: '#/components/parameters/X-CSRF-Header'
      - $ref: '#/components/parameters/fileName'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValueResponse.ScriptResult'
        '400':
          description: Bad Request. Validation exception.
components:
  schemas:
    ValueResponse.ScriptResult:
      description: ValueResponse of ScriptResult type
      allOf:
      - type: object
        properties:
          Value:
            type: object
            properties:
              Content:
                type: string
                example: function CsvReader() {.....}
      - $ref: '#/components/schemas/Response'
    Response:
      type: object
      properties:
        IsSuccess:
          type: boolean
          example: true
        ErrorMessage:
          type: string
          example: ''
        ErrorCode:
          type: string
          example: ''
        ImportJobID:
          description: Import job identification GUID number.
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
  parameters:
    X-CSRF-Header:
      name: X-CSRF-Header
      in: header
      description: 'Required CSRF header for any KeplerService. *Note: Actual string value does not matter*. '
      required: true
      schema:
        type: string
        format: System.String
        default: .
    fileName:
      name: fileName
      in: path
      description: The name of the file to return.
      required: true
      schema:
        type: string
      example: CsvReader.js
