openapi: 3.2.0
info:
  title: Usage Reports Metadata API
  description: Usage Reports is the modern way to gather information and gain oversight across your instance instead of using Relativity scripts, such as Billing Statistics – RelativityOne Case Rollup.
  version: v1
  x-relativity-api-visibility: public
servers:
- url: https://{host}.relativity.one/api/usage-reports
  variables:
    host:
      default: host
      description: Your RelativityOne tenant name
security:
- Bearer: []
tags:
- name: Metadata
paths:
  /v1/Metadata:
    get:
      tags:
      - Metadata
      summary: Gets the metadata
      description: This endpoint retrieves metadata fields required for report creation. The metadata includes fields that are necessary to generate a report or determine the report's content based on the provided ID.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MetadataDto'
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataDto'
            text/json:
              schema:
                $ref: '#/components/schemas/MetadataDto'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      operationId: getV1Metadata
      x-operation-id-source: derived
components:
  schemas:
    MetadataDto:
      type: object
      properties:
        origins:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/MetricOriginDto'
      additionalProperties: false
    MetricOriginDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        metrics:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/MetricDto'
      additionalProperties: false
    MetricDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        valueType:
          enum:
          - Text
          - Int64
          - Double
          - DateTime
          - Boolean
          - Decimal
          type: string
        originId:
          type: string
          format: uuid
        reportType:
          enum:
          - Workspace
          - User
          type: string
        isDefault:
          type: boolean
        isActive:
          type: boolean
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
  securitySchemes:
    Bearer:
      type: http
      description: 'Standard Authorization header using the Bearer scheme. Example: "bearer {token}"'
      scheme: bearer
      bearerFormat: JWT
